version: '3'

services:
  backend:
    build: ./backend
    container_name: tourism-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/alembic/versions:/app/alembic/versions
      - ./backend/alembic/script.py.mako:/app/alembic/script.py.mako
      - ./backend/data:/app/data
    environment:
      - DATABASE_URL=sqlite:///./data/tourism.db
      - SECRET_KEY=your_secret_key_here
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    restart: always
    networks:
      - tourism-network

networks:
  tourism-network:
    driver: bridge 