// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 14.03.2025, 05:45:46
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
import cfg3 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/alex2/Desktop/Vlad-project-tours/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/alex2/Desktop/Vlad-project-tours/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/alex2/Desktop/Vlad-project-tours/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/alex2/Desktop/Vlad-project-tours/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/alex2/Desktop/Vlad-project-tours/frontend/plugins/**/*.{js,ts,mjs}","C:/Users/alex2/Desktop/Vlad-project-tours/frontend/store/**/*.{js,ts,mjs}","C:/Users/alex2/Desktop/Vlad-project-tours/frontend/composables/**/*.{js,ts,mjs}","C:/Users/alex2/Desktop/Vlad-project-tours/frontend/utils/**/*.{js,ts,mjs}","C:/Users/alex2/Desktop/Vlad-project-tours/frontend/pages/about.vue","C:/Users/alex2/Desktop/Vlad-project-tours/frontend/pages/admin/index.vue","C:/Users/alex2/Desktop/Vlad-project-tours/frontend/pages/admin/tours.vue","C:/Users/alex2/Desktop/Vlad-project-tours/frontend/pages/admin/users.vue","C:/Users/alex2/Desktop/Vlad-project-tours/frontend/pages/booking/confirmation.vue","C:/Users/alex2/Desktop/Vlad-project-tours/frontend/pages/booking/index.vue","C:/Users/alex2/Desktop/Vlad-project-tours/frontend/pages/contacts.vue","C:/Users/alex2/Desktop/Vlad-project-tours/frontend/pages/index.vue","C:/Users/alex2/Desktop/Vlad-project-tours/frontend/pages/login.vue","C:/Users/alex2/Desktop/Vlad-project-tours/frontend/pages/profile/index.vue","C:/Users/alex2/Desktop/Vlad-project-tours/frontend/pages/register.vue","C:/Users/alex2/Desktop/Vlad-project-tours/frontend/pages/tours/[id].vue","C:/Users/alex2/Desktop/Vlad-project-tours/frontend/pages/tours/index.vue","C:/Users/alex2/Desktop/Vlad-project-tours/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/alex2/Desktop/Vlad-project-tours/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/alex2/Desktop/Vlad-project-tours/frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;